# Generated by Django 3.0.4 on 2020-03-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldrss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='edited_on',
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
