# Generated by Django 3.0.4 on 2020-03-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldrss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
