# Generated by Django 3.0.4 on 2020-03-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldrss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
