# Generated by Django 3.0.4 on 2020-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldrss', '0002_auto_20200315_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
