# Generated by Django 3.0.4 on 2020-03-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tldrss', '0004_auto_20200318_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',)},
        ),
    ]
