# Generated by Django 3.0.4 on 2020-03-22 03:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tldrss', '0006_auto_20200319_0147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedsubscription',
            unique_together={('user', 'feed')},
        ),
    ]
