# Generated by Django 3.0.4 on 2020-03-24 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tldrss', '0009_articleupvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleupvote',
            unique_together={('user', 'article')},
        ),
    ]
